#!/usr/bin/env python

import os
import sys
import hashlib

hashes = {}
root = sys.argv[1]

for dirpath, _, filenames in os.walk(root):
    commonpath = os.path.commonprefix((dirpath, root))

    for filename in filenames:
        fullpath = os.path.join(dirpath, filename)
        sha = hashlib.sha1(open(fullpath, 'rb').read())
        hashes[fullpath[len(commonpath) + 1:]] = sha.hexdigest()

print "HASHES = %r" % hashes
